### ISSUE TITLE
Some question about the subtraction in the global residual connection

### ISSUE THREAD

**Issue by CuddleSabe** [csslc/PiSA-SR#2]
Thanks for your great work !
"Because DMs are trained to denoise in the in- verse diffusion process, we use subtraction in the global residual connection"
Will the result worse when use plus ?
thanks!

**Comment by csslc** [comment]
Thank you for your interest!
Using plus here will lead to a slower convergence speed and worse visual results than subtraction.

**Comment by CuddleSabe** [comment]
> Thank you for your interest! Using plus here will lead to a slower convergence speed and worse visual results than subtraction.

Thanks  for your reply!
What the "mixed_precision" you set?
thanks

**Comment by CuddleSabe** [comment]
感谢！
复现成功！！
![validation_1007_18f11b83251d755ac63a](https://github.com/user-attachments/assets/6a1dcc4b-2c00-4d3d-a2de-eeaafdb238b9)
![validation_1007_797297bb8e93c0ed0298](https://github.com/user-attachments/assets/449eb17a-1730-45df-90cf-6e9a0d195548)
